### ISSUE TITLE
Feedback'

### ISSUE THREAD

**Issue by MuzaffarNurillaew** [misterpozitiv1607/OnlineCourse#1]
------ Warning'larga umuman e'tibor berilmagan

Domain:
        Relationlar yaxshi qilinmagan
        One-to-many bo'ladi kurs va student

Data:
        +++ Fluent API
        +++ Seed Data
        --- Naming convention MethodNameAsync
        --- interface'lar ishlatilmagan

Service:
        --- Ba'zi joylarda asinxron methodlarga await qo'yilmagan umuman

**Comment by misterpozitiv1607** [comment]
Xa vaqtdan ozgina muammolar bo’ldi keying safar yaxshiroq qilishga xarakat qilaman Feedback uchun raxmat  Отправлено из приложения "Почта" для Windows От: Muzaffar NurillayevОтправлено: 12 августа 2023 г. в 13:17Кому: misterpozitiv1607/OnlineCourseКопия: SubscribedТема: [misterpozitiv1607/OnlineCourse] Feedback' (Issue #1) ------ Warning'larga umuman e'tibor berilmaganDomain:Relationlar yaxshi qilinmaganOne-to-many bo'ladi kurs va studentData:+++ Fluent API+++ Seed Data--- Naming convention MethodNameAsync--- interface'lar ishlatilmaganService:--- Ba'zi joylarda asinxron methodlarga await qo'yilmagan umuman—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by misterpozitiv1607** [comment]
Keyingilaridan xarakat qilamiz

**Comment by misterpozitiv1607** [comment]
> ------ Warning'larga umuman e'tibor berilmagan
> 
> Domain: Relationlar yaxshi qilinmagan One-to-many bo'ladi kurs va student
> 
> Data: +++ Fluent API +++ Seed Data --- Naming convention MethodNameAsync --- interface'lar ishlatilmagan
> 
> Service: --- Ba'zi joylarda asinxron methodlarga await qo'yilmagan umuman

Keyingilaridan xarakat qilamiz bunisiga to'g'risi vaqtdan ozgina qiynaldik testlashga vaqt yetmay qoldi. Feedback uchun raxmat
